/*!
 * imagesLoaded PACKAGED v3.0.4
 * JavaScript is all like "You images are done yet or what?"
 * MIT License
 */
/*!
 * EventEmitter v4.2.4 - git.io/ee
 * Oliver Caldwell
 * MIT license
 * @preserve
 */
(function(){function e(){}var t=e.prototype;function n(e,t){for(var n=e.length;n--;)if(e[n].listener===t)return n;return-1}function i(e){return function(){return this[e].apply(this,arguments)}}t.getListeners=function(e){var t,n,i=this._getEvents();if("object"==typeof e)for(n in t={},i)i.hasOwnProperty(n)&&e.test(n)&&(t[n]=i[n]);else t=i[e]||(i[e]=[]);return t},t.flattenListeners=function(e){var t,n=[];for(t=0;t<e.length;t+=1)n.push(e[t].listener);return n},t.getListenersAsObject=function(e){var t,n=this.getListeners(e);return n instanceof Array&&((t={})[e]=n),t||n},t.addListener=function(e,t){var i,r=this.getListenersAsObject(e),o="object"==typeof t;for(i in r)r.hasOwnProperty(i)&&-1===n(r[i],t)&&r[i].push(o?t:{listener:t,once:!1});return this},t.on=i("addListener"),t.addOnceListener=function(e,t){return this.addListener(e,{listener:t,once:!0})},t.once=i("addOnceListener"),t.defineEvent=function(e){return this.getListeners(e),this},t.defineEvents=function(e){for(var t=0;t<e.length;t+=1)this.defineEvent(e[t]);return this},t.removeListener=function(e,t){var i,r,o=this.getListenersAsObject(e);for(r in o)o.hasOwnProperty(r)&&-1!==(i=n(o[r],t))&&o[r].splice(i,1);return this},t.off=i("removeListener"),t.addListeners=function(e,t){return this.manipulateListeners(!1,e,t)},t.removeListeners=function(e,t){return this.manipulateListeners(!0,e,t)},t.manipulateListeners=function(e,t,n){var i,r,o=e?this.removeListener:this.addListener,s=e?this.removeListeners:this.addListeners;if("object"!=typeof t||t instanceof RegExp)for(i=n.length;i--;)o.call(this,t,n[i]);else for(i in t)t.hasOwnProperty(i)&&(r=t[i])&&("function"==typeof r?o.call(this,i,r):s.call(this,i,r));return this},t.removeEvent=function(e){var t,n=typeof e,i=this._getEvents();if("string"===n)delete i[e];else if("object"===n)for(t in i)i.hasOwnProperty(t)&&e.test(t)&&delete i[t];else delete this._events;return this},t.removeAllListeners=i("removeEvent"),t.emitEvent=function(e,t){var n,i,r,o=this.getListenersAsObject(e);for(r in o)if(o.hasOwnProperty(r))for(i=o[r].length;i--;)!0===(n=o[r][i]).once&&this.removeListener(e,n.listener),n.listener.apply(this,t||[])===this._getOnceReturnValue()&&this.removeListener(e,n.listener);return this},t.trigger=i("emitEvent"),t.emit=function(e){var t=Array.prototype.slice.call(arguments,1);return this.emitEvent(e,t)},t.setOnceReturnValue=function(e){return this._onceReturnValue=e,this},t._getOnceReturnValue=function(){return!this.hasOwnProperty("_onceReturnValue")||this._onceReturnValue},t._getEvents=function(){return this._events||(this._events={})},"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],(function(){return e})):"object"==typeof module&&module.exports?module.exports=e:this.EventEmitter=e}).call(this),
/*!
 * eventie v1.0.3
 * event binding helper
 *   eventie.bind( elem, 'click', myFn )
 *   eventie.unbind( elem, 'click', myFn )
 */
function(e){var t=document.documentElement,n=function(){};t.addEventListener?n=function(e,t,n){e.addEventListener(t,n,!1)}:t.attachEvent&&(n=function(t,n,i){t[n+i]=i.handleEvent?function(){var t=e.event;t.target=t.target||t.srcElement,i.handleEvent.call(i,t)}:function(){var n=e.event;n.target=n.target||n.srcElement,i.call(t,n)},t.attachEvent("on"+n,t[n+i])});var i=function(){};t.removeEventListener?i=function(e,t,n){e.removeEventListener(t,n,!1)}:t.detachEvent&&(i=function(e,t,n){e.detachEvent("on"+t,e[t+n]);try{delete e[t+n]}catch(i){e[t+n]=void 0}});var r={bind:n,unbind:i};"function"==typeof define&&define.amd?define("eventie/eventie",r):e.eventie=r}(this),
/*!
 * imagesLoaded v3.0.4
 * JavaScript is all like "You images are done yet or what?"
 * MIT License
 */
function(e){var t=e.jQuery,n=e.console,i=void 0!==n;function r(e,t){for(var n in t)e[n]=t[n];return e}var o=Object.prototype.toString;function s(e){var t=[];if(function(e){return"[object Array]"===o.call(e)}(e))t=e;else if("number"==typeof e.length)for(var n=0,i=e.length;n<i;n++)t.push(e[n]);else t.push(e);return t}function a(e,o){function a(e,n,i){if(!(this instanceof a))return new a(e,n);"string"==typeof e&&(e=document.querySelectorAll(e)),this.elements=s(e),this.options=r({},this.options),"function"==typeof n?i=n:r(this.options,n),i&&this.on("always",i),this.getImages(),t&&(this.jqDeferred=new t.Deferred);var o=this;setTimeout((function(){o.check()}))}a.prototype=new e,a.prototype.options={},a.prototype.getImages=function(){this.images=[];for(var e=0,t=this.elements.length;e<t;e++){var n=this.elements[e];"IMG"===n.nodeName&&this.addImage(n);for(var i=n.querySelectorAll("img"),r=0,o=i.length;r<o;r++){var s=i[r];this.addImage(s)}}},a.prototype.addImage=function(e){var t=new f(e);this.images.push(t)},a.prototype.check=function(){var e=this,t=0,r=this.images.length;if(this.hasAnyBroken=!1,r)for(var o=0;o<r;o++){var s=this.images[o];s.on("confirm",a),s.check()}else this.complete();function a(o,s){return e.options.debug&&i&&n.log("confirm",o,s),e.progress(o),++t===r&&e.complete(),!0}},a.prototype.progress=function(e){this.hasAnyBroken=this.hasAnyBroken||!e.isLoaded;var t=this;setTimeout((function(){t.emit("progress",t,e),t.jqDeferred&&t.jqDeferred.notify(t,e)}))},a.prototype.complete=function(){var e=this.hasAnyBroken?"fail":"done";this.isComplete=!0;var t=this;setTimeout((function(){if(t.emit(e,t),t.emit("always",t),t.jqDeferred){var n=t.hasAnyBroken?"reject":"resolve";t.jqDeferred[n](t)}}))},t&&(t.fn.imagesLoaded=function(e,n){return new a(this,e,n).jqDeferred.promise(t(this))});var c={};function f(e){this.img=e}return f.prototype=new e,f.prototype.check=function(){var e=c[this.img.src];if(e)this.useCached(e);else if(c[this.img.src]=this,this.img.complete&&void 0!==this.img.naturalWidth)this.confirm(0!==this.img.naturalWidth,"naturalWidth");else{var t=this.proxyImage=new Image;o.bind(t,"load",this),o.bind(t,"error",this),t.src=this.img.src}},f.prototype.useCached=function(e){if(e.isConfirmed)this.confirm(e.isLoaded,"cached was confirmed");else{var t=this;e.on("confirm",(function(e){return t.confirm(e.isLoaded,"cache emitted confirmed"),!0}))}},f.prototype.confirm=function(e,t){this.isConfirmed=!0,this.isLoaded=e,this.emit("confirm",this,t)},f.prototype.handleEvent=function(e){var t="on"+e.type;this[t]&&this[t](e)},f.prototype.onload=function(){this.confirm(!0,"onload"),this.unbindProxyEvents()},f.prototype.onerror=function(){this.confirm(!1,"onerror"),this.unbindProxyEvents()},f.prototype.unbindProxyEvents=function(){o.unbind(this.proxyImage,"load",this),o.unbind(this.proxyImage,"error",this)},a}"function"==typeof define&&define.amd?define(["eventEmitter/EventEmitter","eventie/eventie"],a):e.imagesLoaded=a(e.EventEmitter,e.eventie)}(window);